### ISSUE TITLE
引用有道接口时使用https

### ISSUE THREAD

**Issue by xiebruce** [jiangqizheng/BlueSea#15]
如下图，目前用的是http，我试了https是没问题的，因为http会导致chrome浏览器左上角的小锁显示成不安全
![image](https://user-images.githubusercontent.com/13575500/102082404-deb87800-3e4c-11eb-84f2-8ae22658185f.png)

**Comment by jiangqizheng** [comment]
已替换

**Comment by xiebruce** [comment]
👍
