### ISSUE TITLE
过去式动词收藏后转换为动词原型，无法在网页上显示

### ISSUE THREAD

**Issue by al123xiaaaa** [jiangqizheng/BlueSea#2]
其实主动做构词法转换是很好的，但是得想办法匹配单词在网页上对应的形态

![lecture](https://user-images.githubusercontent.com/6868760/101977922-1fb55e80-3c8c-11eb-8eea-a90281b4ce74.PNG)

**Comment by al123xiaaaa** [comment]
和 #1 重复

**Comment by al123xiaaaa** [comment]
Duplicate of #1

**Comment by jiangqizheng** [comment]
已经修复了，新增了textExts字段，用于处理非原型情况。后面考虑参考扇贝单词，单词派生的形式，将同单词的不同形式，集合在一起。
