### ISSUE TITLE
[功能增强]希望能自定义弹幕速度

### ISSUE THREAD

**Issue by xiebruce** [jiangqizheng/BlueSea#4]
如题，每个人可能有他适应的速度，有些人可能希望快一点，有些人可能希望慢一点，所以建议做成在一定的范围内速度可调比较好。

**Comment by jiangqizheng** [comment]
已支持

**Comment by xiebruce** [comment]
这么速度！👍🏻

**Comment by xiebruce** [comment]
可以可以
![弹幕速度](https://i.imgur.com/8RAhbGi.gif)
