### ISSUE TITLE
怎么查看配置呀？

### ISSUE THREAD

**Issue by Joycejzy** [jiangqizheng/BlueSea#40]
怎么查看配置呀？配置中心怎么打开， 是在地址栏旁边有个L的图标吗，我的 chrome browse  没有这个图标
我的 chrome browse Version 87.0.4280.88

**Comment by jiangqizheng** [comment]
是不是插件过多导致被隐藏了？地址栏最右侧是不是有一个"拼图"的图标，点击后，将BlueSea固定就行。
