### ISSUE TITLE
在不同的网站里单词字体大小不同 甚至有些大到超出了黑色背景

### ISSUE THREAD

**Issue by xiebruce** [jiangqizheng/BlueSea#42]
我使用的版本是当前(2020-12-21 22:15)最新的从github上pull下来的

---

在[这个页面](http://mbd.baidu.com/webpage?type=live&action=liveshow&room_id=4094149839&source=search)显示的非常大，144px，属于样式错乱了
![image](https://user-images.githubusercontent.com/13575500/102785116-674c9080-43d8-11eb-9731-042752853594.png)

在[这个页面](https://baike.baidu.com/item/wonderful%20u/19836314?fr=aladdin)大小是12px
![image](https://user-images.githubusercontent.com/13575500/102785183-80554180-43d8-11eb-9a27-88fbd57e8b95.png)

在[youtube](https://www.youtube.com/watch?v=3B30l15xTSk)页面大小是10px
![image](https://user-images.githubusercontent.com/13575500/102784921-0a50da80-43d8-11eb-8ad6-36ff81140d5c.png)

在[github](https://github.com/)页面，它的大小是14px
![image](https://user-images.githubusercontent.com/13575500/102784987-25bbe580-43d8-11eb-8bb2-f1144af835cc.png)

**Comment by jiangqizheng** [comment]
感谢反馈，可能是由于某些网站内部针对span定义一些全局样式导致的。刚刚fix了一下，现在已经正常了。😃

**Comment by xiebruce** [comment]
更新后看了一下，确实没问题了。我更新的方式都是删除扩展后重新添加，发现所有配置都恢复到默认，无法保存配置，这是个问题！
