### ISSUE TITLE
【建议】弹幕窗口添加个复制按钮

### ISSUE THREAD

**Issue by xiebruce** [jiangqizheng/BlueSea#43]
当我看到单词弹幕时，我有时候想用词典查这个词，但是想划选手动复制都复制不了，只能手动敲，太麻烦
![image](https://user-images.githubusercontent.com/13575500/102849242-b1be2380-4451-11eb-9ec8-58cf678a66e3.png)

如果能有一个像这样的按钮([按钮文件链接](https://clipboardjs.com/assets/images/clippy.svg))在右上角，我点一下就能复制单词，会比较方便
![image](https://user-images.githubusercontent.com/13575500/102846401-db278100-444a-11eb-9e7b-9c825d83571f.png)

**Comment by jiangqizheng** [comment]
这是feature，为了增强学习效果，让你再输入一遍，对单词印象更深刻😃。




——下次迭代的时候加上。

**Comment by xiebruce** [comment]
哈哈，好的
