### ISSUE TITLE
创意来源不会是弹幕记忆APP吧

### ISSUE THREAD

**Issue by mythoi** [jiangqizheng/BlueSea#46]
创意来源不会是“弹幕记忆APP”吧，背单词的模式差不多一样。https://word.mythoi.cn

**Comment by jiangqizheng** [comment]
并不是，最初主要是希望为到复习时间点的单词给予用户一个提醒。
早期和朋友讨论时考虑了浏览器推送、popup的角标、全局的悬浮窗、以及其他各类形态。
后面由于本身天天逛b站，看到弹幕突然感觉还不错，所以才准备以弹幕的形式进行提醒。

***

并且弹幕在插件中仅作为一个提醒机制，一个非主要的功能而已，后续可能会被更友好、有趣的形式替换。在介绍中也可以看出，其仅仅是功能之一。
> BlueSea，是一个有趣的英语学习扩展程序。支持划词翻译、单词高亮、单词弹幕、记忆曲线复习、词频统计...等功能。

***

另外，我认为你这个提问是很没有礼貌的行为。你不能因为看到类似的创意，然后就没有任何依据的，跑出来说，你的创意是不是来源于xxx。（并且这个xxx本身也不是唯一，刚刚搜索了一下，“弹幕学英语” 的关键词，能搜出不少应用）。
