### ISSUE TITLE
谢谢作者 插件特别好用。这里提一个优化的点

### ISSUE THREAD

**Issue by liliangrong777** [jiangqizheng/BlueSea#66]
谢谢作者写的这个插件，真的特别好用。
不过如果能在单词详情再加上一个删除按钮就好了。
这样对于已经记住的单词就不用特意跑到列表里边去删减了，感觉会方便很多。
![image](https://user-images.githubusercontent.com/58727146/186601665-b604af08-b376-4fc0-b6cf-ad2bef3367de.png)

**Comment by jiangqizheng** [comment]
收到
