### ISSUE TITLE
[Feature]划词功能对输入框内的文字无效

### ISSUE THREAD

**Issue by code-twelve** [jiangqizheng/BlueSea#8]
你好 划词功能似乎对输入框内的文字不起作用 例如在搜索栏里选中单词 并没有弹出翻译并发音

**Comment by jiangqizheng** [comment]
我认为对输入框内文字不起作用是合理的。毕竟输入框主要是在输入内容。

**Comment by code-twelve** [comment]
你说的有道理 不过我昨天发现这个问题的场景是：从 word/pdf 中拿出一段英文到网页里翻译 有某些生词想要记录并学习但在输入框内无法划取 
就我个人而言 使用翻译网页的输入框 更多的是复制粘贴 而不是键盘输入  
并且对英语学习者来说 一段话理解大意后记录一些生词 是很自然的操作 所以我个人认为输入框内划词这个功能还是有必要的 并且建议能够提供控制该功能开关的选项会更好一些 这样该功能也不会对键盘输入的场景产生干扰
